config/routes.rb
Rails.application.routes.draw do
  get 'collaborators/create'
  get 'collaborators/destroy'
  get 'charges/new'
  get 'charges/create'

  resources :wikis do
    resources :collaborations, only: :create
  end
  resources :collaborations, only: [:destroy]
  resources :charges, only: [:new, :create, :destroy]
  devise_for :users
  get 'about' => 'welcome#about'
  get 'downgrade' => 'users#downgrade'
  root 'welcome#index'
  

end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  after_initialize :default_to_standard
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :collaborations
  has_many :wikis
  has_many :shared_wikis, through: :collaborations, source: :wiki
  enum role: [:standard, :premium, :admin]
  
  after_save :publish_wikis

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

  private

  def default_to_standard
    self.role = 'standard' if self.role.nil?
  end
  
    
  def publish_wikis
    return if role_was == 'standard' && role =='standard'
    
    if role == 'standard'
      wikis.where(private:true).each do |j|
        j.private = false
        j.save
      end
    end
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborations
  has_many :users, through: :collaborations
  scope :visible_to, -> (user) { user ? all : where(private: false) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user! 
  protect_from_forgery with: :exception
  
  
  private 
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @amount = 1500
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "BigMoney Membership - #{current_user.email}",
      amount: @amount
    }
  end

  def create
    @amount = 1500
    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
      )
      
    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: "BigMoney Membership - #{current_user.email}",
      currency: 'usd'
      )
    current_user.premium!
    flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
    redirect_to wikis_path
    
    rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController

  
  def create
    wiki = Wiki.find(params[:wiki_id])
    user = User.find_by(email: params[:search])
    
    if user
      collaboration = Collaboration.new(wiki: wiki, user: user)
      authorize collaboration
      if collaboration.save
        flash[:notice] = "Collaborator was saved."
        redirect_to wiki_path(wiki)
      else
        flash.now[:error] = "There was an error saving the Collaborator. Please try again."
      end
    end
  end
  

  def destroy
    collaboration = Collaboration.find(params[:id])
    authorize collaboration
    wiki = collaboration.wiki
    if collaboration.destroy
      flash[:notice] = "Collaborator removed"
      redirect_to wiki
    else
      flash.now[:alert] = "Error"
      render :show
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = current_user
  end
  
  def downgrade
    if current_user.premium?
      current_user.standard!
      flash[:notice] = "You have been downgraded to standard."
      redirect_to root_path
    else
      flash[:error] = "There was an error downgrading your account. Please try again."
      redirect_to edit_user_registration_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
 before_action :authenticate_user!, except: [:index, :show]
  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    unless @wiki.private == false || current_user 
    flash[:alert] = "You must be signed in to view private topics."
    redirect_to wikis_path
    end
    authorize @wiki
    
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end
  
  def create 
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    authorize @wiki
    
    if @wiki.save
      flash[:notice] = "Wiki page was saved successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the Wiki page. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end
  
  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    authorize @wiki
    
    if @wiki.save
      flash[:notice] = "Wiki page was updated successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving your page. Please try again."
      render :edit
    end
  end
  
  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the page."
      render :show
    end
  end
  
      private
    def wiki_params
      if current_user && current_user.premium?
        params.require(:wiki).permit(:title, :body, :private)
      else
        params.require(:wiki).permit(:title, :body)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
  <%= form_tag charges_path do %>
    <h4>Click the button!</h4>
    <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%=
@stripe_btn_data[:key] %>"data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%=
@stripe_btn_data[:description] %>" ></script>
  <% end %>

app/views/collaborations/_collaborations.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <h4>Collaborators</h4>
  </div>
    <% if current_user %>
      <%= render partial: 'collaborations/form', locals: { wiki: wiki, collaboration: collaboration } %>
    <% end %>
    <% wiki.collaborations.each do |collab| %>
    <%= collab.user.email %>
    <%= link_to "Remove", collab, method: :delete, data: { confirm: 'Are you sure you want to remove this user?'} %>
    <% end %>
  </div>
</div>

app/views/collaborations/_form.html.erb
<%= form_tag(wiki_collaborations_path(params[:id]), method: 'post') do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Add User" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Wikis", wikis_path %></li>
  </ul>
  <% if user_signed_in? %>
    Signed in as: <strong><%= current_user.email %></strong>
    <%= image_tag current_user.avatar_url(24), class: "gravatar" %>|
    <%= link_to 'Edit profile' , edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
  <% else %>
    <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> -
    <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
  <% end %>
  
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss"alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
  <% end %>
    </div>
  <%= yield %>
</div>

</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/about.html.erb
<h1>About Blocipedia</h1>
<p>Created by: Josh Anderson</p>

app/views/welcome/index.html.erb
<h1>Welcome to Blocipedia</h1>
<p>Home page for Blocipedia</p>

app/views/wikis/_form.html.erb
<div class="form-group">
        <%= f.label :title %>
        <%=f.text_field :title, class: 'form-control', placeholder: "Enter Wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter Wiki body" %>
      </div>
      <div class="form group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
<% if current_user.admin? || current_user.premium? %>
  <div class="form-group">
    <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> Private wiki
    <% end %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for your Wiki</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter 'A'</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class ="form-group">
        <%= render partial: 'wikis/form', locals: { f: f, private: @wiki.private} %>
      </div>
    <% end %>
  </div>
    <div class="col-md-8">
    <% if @wiki.private? %>
      <%= render partial: 'collaborations/collaborations', locals: { wiki: @wiki, collaboration: @collaboration } %>
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<div class="row">
  <div class="col-md-8">
    <% @wikis.each do |wiki| %>
      <div class ="media">
        <div class ="media-body">
          <h4 class="media-heading">
            <%= link_to wiki.title, wiki %>
          </h4>
        </div>
      </div>
    <% end %>
    <div class="col-md-4">
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki Page</h1>
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for your Wiki</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter 'A'</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class ="form-group">
        <%= render partial: 'wikis/form', locals: { f: f, private: @wiki.private} %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>
<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this Page?'} %>
  </div>
  <div class="hidden">
    <% if @wiki.private? %>
      <%= render partial: 'collaborations/collaborations', locals: { wiki: @wiki, collaboration: @collaboration } %>
    <% end %>
  </div>
</div>